### ISSUE TITLE
Conectar a Identificação de Câmeras à API

### ISSUE THREAD

**Issue by CodeWracker** [LSIIM/Programa-de-Captura-Web#12]
**Descrição:**
Implementar a lógica de identificação de câmeras conectadas ao computador via API, transformando os placeholders em vídeos ao vivo. O sistema deve permitir atribuir funções às câmeras e enviar essas informações à API.

**TODO:**
- [ ] Implementar GET para buscar as câmeras conectadas via API.
- [ ] Exibir o feed de vídeo ao vivo para cada câmera conectada.
- [ ] Implementar lógica de atribuição de funções às câmeras.
- [ ] Enviar as atribuições à API.

**Resultado esperado:**
A identificação e atribuição de funções às câmeras devem estar conectadas à API e funcionais.
