### ISSUE TITLE
Conectar a Listagem de Vídeos Gravados à API

### ISSUE THREAD

**Issue by CodeWracker** [LSIIM/Programa-de-Captura-Web#14]
**Descrição:**
Conectar a listagem de vídeos gravados à API, permitindo que os vídeos sejam carregados dinamicamente e exibidos com suas informações (paciente, projeto, movimento), além de permitir filtros e ordenação.

**TODO:**
- [ ] Implementar GET para buscar a lista de vídeos gravados da API.
- [ ] Exibir as informações dos vídeos e status de processamento.
- [ ] Implementar filtros e ordenação com dados reais.

**Resultado esperado:**
A listagem de vídeos deve ser funcional, carregando dados da API e permitindo a filtragem e ordenação.
