### ISSUE TITLE
Conectar o Processamento de Vídeos à API

### ISSUE THREAD

**Issue by CodeWracker** [LSIIM/Programa-de-Captura-Web#16]
**Descrição:**
Conectar a funcionalidade de processamento de vídeos à API, permitindo que os vídeos sejam enviados para a fila de processamento do eyetracker. Deve haver a opção de processamento em lote.

**TODO:**
- [ ] Implementar POST para enviar vídeos para a fila de processamento.
- [ ] Implementar lógica de processamento em lote.
- [ ] Exibir status de processamento (opcional).

**Resultado esperado:**
O processamento de vídeos deve estar funcional, com possibilidade de envio em lote.
