### ISSUE TITLE
Criar tela de Seleção de Pacientes para gravação (estática)

### ISSUE THREAD

**Issue by CodeWracker** [LSIIM/Programa-de-Captura-Web#2]
**Descrição:**
Desenvolver a tela de seleção de pacientes, onde os pacientes serão exibidos como cards ou em formato de tabela. Também deve haver um botão de "Adicionar Paciente", que abre um modal (sem funcionalidade de cadastro real nesta etapa).

**TODO:**
- [x] Criar uma lista estática de pacientes exibida como cards ou tabela.
- [x] Adicionar barra de busca (apenas UI, sem lógica de pesquisa).
- [x] Adicionar o botão "Adicionar Paciente" que abre um modal de cadastro (apenas UI).
- [x] Estilizar o modal de cadastro de paciente.

**Resultado esperado:**
A tela de seleção de pacientes deve estar estática, com lista de pacientes e botão para abrir o modal de cadastro (sem funcionalidade real).
