### ISSUE TITLE
Desenvolver Tela de Visualização de Vídeos Gravados (estática)

### ISSUE THREAD

**Issue by CodeWracker** [LSIIM/Programa-de-Captura-Web#8]
**Descrição:**
Criar a interface de visualização de vídeos gravados. Os vídeos serão exibidos como placeholders ou os vídeos locais gravados na etapa anterior. Deve exibir vídeos das câmeras primária e secundária, e incluir o vídeo processado (simulado).

**TODO:**
- [ ] Adicionar placeholders para os vídeos gravados das câmeras primária e secundária.
- [ ] Adicionar vídeo processado (simulado) com controles de reprodução.
- [ ] Estilizar a interface para acomodar múltiplos vídeos.

**Resultado esperado:**
A tela de visualização dos vídeos deve exibir os vídeos gravados e processados de maneira estática, com controles de reprodução simulados.
